### ISSUE TITLE
demos/battle can not run catch ClassMirrorNotFoundException: java.lang.Object error messages

### ISSUE THREAD

**Issue by leex12** [nqzero/kilim#1]
Exception in thread "main" java.lang.AssertionError: class-based lookup should never fail
	at kilim.mirrors.CachedClassMirrors.mirror(CachedClassMirrors.java:87)
	at kilim.mirrors.Detector.<init>(Detector.java:38)
	at kilim.analysis.KilimContext.<init>(KilimContext.java:13)
	at kilim.analysis.KilimContext.<clinit>(KilimContext.java:8)
	at kilim.WeavingClassLoader.<init>(WeavingClassLoader.java:81)
	at kilim.tools.Kilim.run(Kilim.java:35)
	at kilim.tools.Kilim.trampoline(Kilim.java:59)
	at kilim.demo.Battle.main(Battle.java:48)
Caused by: kilim.mirrors.ClassMirrorNotFoundException: java.lang.Object
	at kilim.mirrors.CachedClassMirrors.classForName(CachedClassMirrors.java:54)
	at kilim.mirrors.CachedClassMirrors.mirror(CachedClassMirrors.java:84)
	... 7 more

**Comment by leex12** [comment]
windows 7

**Comment by nqzero** [comment]
i am traveling for the weekend. i'll try to take a look this evening, but i may not have a chance until i return home on tuesday. thanks for the bug report

**Comment by nqzero** [comment]
i don't have access to a win7 box. it looks like i'm using the wrong separator character when converting from canonical to class names

WeavingClassLoader:
    public static String map(String name) { return name.replace('.', File.separatorChar) + ".class"; }

i'll look for a windows box at work. if you want to try fixing it yourself, replace File.separatorChar with "/" or "\"

**Comment by nqzero** [comment]
i've pushed 2.0.0-10 which should fix this - can you try it ?

**Comment by leex12** [comment]
it's working! 
thank you so much!
