### ISSUE TITLE
woven lambdas cause NoClassDefFoundError in java 10

### ISSUE THREAD

**Issue by nqzero** [nqzero/kilim#7]
woven lambdas fail to load in java 10, eg:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Win$$Lambda$3
	at Win$$Lambda$3/1915058446.get$Lambda(Unknown Source)
	at Win.main(Win.java:46)
Caused by: java.lang.ClassNotFoundException: Win$$Lambda$3
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 2 more
```

**Comment by nqzero** [comment]
when kilim weaves a Pausable lambda without a `Fiber` argument (prior to 2.0.0-17 this was all woven lambdas) it adds a `Fiber` argument, leaving the original abstract method abstract. java 8 and 9 didn't complain, but java 10 appears to silently reject them

to work around this issue, provide a dummy `Fiber` as the last parameter in the abstract interface method

**Comment by nqzero** [comment]
https://github.com/nqzero/kilim/tree/2.0.0-17
